#!/usr/bin/env bash

root_repo="basex"
init_commit="Initial commit of unified BaseX repository"

core_repo_name="upstream-basex-core"
api_repo_name="upstream-basex-api"

core_repo_url="git://github.com/BaseXdb/basex.git"
api_repo_url="git://github.com/BaseXdb/basex-api.git"

core_repo_url="$HOME/Development/basex/basex-core"
api_repo_url="$HOME/Development/basex/basex-api"

message="Merged git repositories in a single one"

function merge_git_tree() {
  repo_name="$1"
  repo_url="$2"
  subdir="$3"
  tmp_index=".git/tmp-$repo_name-index"

  # add remote repository url and fetch all commits, branches, and tags
  git remote add -f "$repo_name" "$repo_url"

  # read the fetched tree into a temporary index file
  GIT_INDEX_FILE="$tmp_index" git read-tree FETCH_HEAD

  # checkout all files from the temporary index file in a subdirectory
  GIT_INDEX_FILE="$tmp_index" git checkout-index --all --index --prefix="$subdir/"

  # add all files from the temporary index to the actual index
  git update-index --add -- $(GIT_INDEX_FILE="$tmp_index" git ls-files)

  # mark the fetched heads as merge heads
  cat ".git/FETCH_HEAD" >> ".git/MERGE_HEAD"

  return 0
}

rm -fR "$root_repo"
git init "$root_repo"
cd "$root_repo"

touch readme.md
git add readme.md
git commit -m "$init_commit"

merge_git_tree "$core_repo_name" "$core_repo_url" "basex-core"
merge_git_tree "$api_repo_name" "$api_repo_url" "basex-api"

git commit --message="$message"

